config/routes.rb
Rails.application.routes.draw do
  get 'confirmations/show'
  get 'confirmations_controller/show'

  root 'static_pages#home'
  get  'help'    => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  #get  'signup'  => 'users#new'
  devise_for :users, 
              controllers: { registrations: "registrations", sessions: "sessions"}                     

  devise_scope :user do
    # as: :login -> named route, now we can use register_path
    get    "login"    => "devise/sessions#new",      as: :login 
    get    "register" => "devise/registrations#new", as: :register
    delete "logout"   => "devise/sessions#destroy",  as: :logout
  end                                  

  resources :users do
    member do
      get "following", to: "users#following"  
      get "followers", to: "users#followers"  
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable       

  validates :name,  presence: true, length: { maximum: 50 }    

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  
  # Returns a user's status feed
  def feed
  	following_ids_subselect = "SELECT followed_id FROM relationships WHERE follower_id = :user_id" 
    Micropost.where("user_id IN (#{following_ids_subselect}) OR user_id = :user_id", user_id: self.id)
  end

  # Follows a user.
	# user.active_relationships.create(followed_id: user.id) - creates an active relationship 
	# associated with user
	# follower is impicit because Rails know on which object these methods are called
	def follow(other_user)
		active_relationships.create(followed_id: other_user.id)
	end

	# Unfollows a user.
	def unfollow(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	# Returns true if the current user is following the other user.
	def following?(other_user)
		# if these exists, it's return true
		# => !active_relationships.find_by(followed_id: other_user.id).nil?
		# better way
		# we can do this because of this
		# has_many	:following, through: :active_relationships, source: :followed
		following.include?(other_user) # same as -> self.following.include?(other_user)		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	#before_action :correct_user, only: :show
  before_action :admin_user, only: :destroy

	def index
		@users = User.paginate(page: params[:page])
	end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    @micropost = current_user.microposts.build
  end

  def destroy
    redirect_to root_url
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = 'Following'
    @user = params[:id] != nil ? User.find(params[:id]) : current_user
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = params[:id] != nil ? User.find(params[:id]) : current_user
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def incorrect_user_path_for
    root_url
  end

  # Confirms the correct user
  def correct_user
    if !is_correct_user
      redirect_to incorrect_user_path_for
    end
  end

  def is_correct_user
  	@user = User.find(params[:id])
    @user == current_user
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin? 
  end
  
end
 

app/helpers/users_helper.rb
module UsersHelper

	# Return  the Gravatar for given user
	def gravatar_for(user, options={size: 80, className: "gravatar"})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}" 
		image_tag(gravatar_url, alt: user.name, class: options[:className])
	end
	
end

app/views/users/forms/_register_new_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
  
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
  </div>

  <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/forms/_session_form.html.erb
<%= form_for(:user, as: resource_name, url: session_path(:user)) do |f| %>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="form-group">
      <div class="col-sm-8">
        <div class="checkbox">
          <%= f.label :remember_me %>
          <%= f.check_box :remember_me, class: "check_box_front" %>    
        </div>
      </div>
    </div>
  <% end -%>
  
  <%= f.submit "Log In", class: "btn btn-primary btn-block" %>
  
<% end %>

<p>
  <%= link_to "Forgot your password?", new_password_path(:user) %>
</p> 