config/routes.rb
Rails.application.routes.draw do
  get 'confirmations/show'
  get 'confirmations_controller/show'

  root 'static_pages#home'
  get  'help'    => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  #get  'signup'  => 'users#new'
  devise_for :users, 
              controllers: { registrations: "registrations", sessions: "sessions"}                     

  devise_scope :user do
    # as: :login -> named route, now we can use register_path
    get    "login"    => "devise/sessions#new",      as: :login 
    get    "register" => "devise/registrations#new", as: :register
    delete "logout"   => "devise/sessions#destroy",  as: :logout
  end                                  

  resources :users do
    member do
      get "following", to: "users#following"  
      get "followers", to: "users#followers"  
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>	
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>		
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<div class="list-group">
		<li class="list-group-item disabled">Tweets</li>
		<%= render @feed_items %>
	</div>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h4 class="text-muted">Compose new Tweet</h4>
	</div>

	<div class="panel-body">
	<%= form_for(@micropost, html: { multipart: true }) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<div class="field">
			<%= f.text_area :content, placeholder: "Compose new post..." %>
		</div>
		
		<%= f.submit "Post", class: 'btn btn-primary' %>

		<div class="picture">
			<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
		</div>
	<% end %>

	<script>
		$("#micropost_picture").on("change", function(){
			size_in_megabytes = this.files[0].size/1024/1024;
			if(size_in_megabytes > 1){
				alert("Maximum file size iz 5MB. Please choose a smaller file.");
			}
		});
	</script>

	</div>
</div>

app/views/shared/_stats.html.erb
<% @user = @user || current_user %>

<div class="row">
	<div class="col-md-4 bg-primary">
		<span class="stats-font-big">
			<strong class="stat"><%= @user.microposts.count %></strong> microposts
		</span>
	</div>
	<div class="col-md-2">
		<a href="<%= following_user_path(@user) %>">
			<span class="stats-font">
		  	<strong id="following">
					<%= @user.following.count %>
				</strong>
				following
				</span>
		</a>
	</div>
	<div class="col-md-2">
		<a href="<%= followers_user_path(@user) %>">
			<span class="stats-font">
		  	<strong id="followers">
					<%= @user.followers.count %>
				</strong>
				followers
			</span>
		</a>
	</div>

	<div class="col-md-1"></div>

	<div class="col-md-3">
		<%= render 'follow_form' if user_signed_in? && !current_user?(@user) %>
	</div>
</div>

app/views/shared/_user_info.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h4><%= link_to current_user.name, current_user %></h4>
	</div>
	
	<div class="panel-body">
		<div class="row profile-w">
			<div class="col-md-10">
				<%= link_to gravatar_for(current_user, size: 140, className: "img-thumbnail"), current_user %>
				<h4><%= link_to current_user.email, current_user %></h4>
			</div>
		</div>
	</div>

	<div class="panel-footer">
		<p class="text-info">
			<strong>
				<%= link_to pluralize(current_user.microposts.count, "tweet"), current_user %>
			</strong>
		</p>
	</div>
</div>