config/routes.rb
Rails.application.routes.draw do
  get 'confirmations/show'
  get 'confirmations_controller/show'

  root 'static_pages#home'
  get  'help'    => 'static_pages#help'
  get  'about'   => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  #get  'signup'  => 'users#new'
  devise_for :users, 
              controllers: { registrations: "registrations", sessions: "sessions"}                     

  devise_scope :user do
    # as: :login -> named route, now we can use register_path
    get    "login"    => "devise/sessions#new",      as: :login 
    get    "register" => "devise/registrations#new", as: :register
    delete "logout"   => "devise/sessions#destroy",  as: :logout
  end                                  

  resources :users do
    member do
      get "following", to: "users#following"  
      get "followers", to: "users#followers"  
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		MG Social Site by Miroslav Gojic. <%= link_to "Contact email", 'mailto: miroslav.gojic.78@gmail.com' %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Rails Guide", "http://guides.rubyonrails.org/index.html" %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Mg Social Site", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to 'Users', users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Profile', current_user %></li>
							<li><%= link_to 'Settings', edit_user_registration_path %></li>
							<li class="divider"></li>
							<li><%= link_to "Logout", logout_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log In", login_path %></li>
					<li><%= link_to "Register", register_path %></li>
				<% end %>	
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="<%= flash_class name %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
	<%= render "layouts/header" %>
	
	<div class="app-background">
	<div class="container">
		<%= render 'layouts/messages' %>	

		<%= yield %>

		<%= render 'layouts/footer' %>	
	</div>
	</div>

	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/device_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
<%= render "layouts/header" %>

<div class="container">
	<%= yield %>

	<%= render 'layouts/footer' %>
	
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/layouts/devise_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
	<%= render "layouts/header" %>

  <div class="app-background">
	<div class="container">
		<%= render 'layouts/messages' %>	

		<%= yield %>

		<%= render 'layouts/footer' %>	
	</div>
	</div>

	<%= debug(params) if Rails.env.development? %>
	
</body>
</html>

app/views/layouts/front_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
	<%= render "layouts/header" %>

	<div class="container">
		<%= render 'layouts/messages' %>	

		<%= yield %>

		<%= render 'layouts/footer' %>	
	</div>


	<%= debug(params) if Rails.env.development? %>

<script>
	$.backstretch([
		"<%= asset_path("background1.jpg", alt: "Rails logo") %>",
		"<%= asset_path("background2.jpg", alt: "Rails logo") %>",
		"<%= asset_path("background3.jpg", alt: "Rails logo") %>",
		"<%= asset_path("background4.jpg", alt: "Rails logo") %>"
	], {duration: 3000, fade: 750});
</script>
</body>
</html>

app/views/layouts/static_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
	<%= render "layouts/header" %>

	<div class="container">
		<%= render 'layouts/messages' %>	

		<%= yield %>

		<%= render 'layouts/footer' %>	
	</div>

	<%= debug(params) if Rails.env.development? %>

</body>
</html>